export const CANCEL_SAVE = "TRADE.CANCEL_SAVE";
export const CLEAR_TRADE_FILTERS = "TRADE.CLEAR_TRADE_FILTERS";
export const CREATE_NEW  = "TRADE.CREATE_NEW";
export const EDIT_TRADE = "TRADE.EDIT_TRADE";
export const FILTER_TRADES = "TRADE.FILTER_TRADES";
export const SELECT_TRADE = "TRADE.SELECT_TRADE";
export const SORT_TRADES = "TRADE.SORT_TRADES";